version: '3'

services:
    main-service:
        build:
            context: ..
            dockerfile: .devcontainer/Dockerfile
        volumes:
            - ..:/workspace
            - ../data:/data
        ports: 
            - 8000:8000
        command: sleep infinity