name: docker-conda-env

dependencies: 
    - keras-gpu
    - python=3.6
    - pylint
    - numpy
    - xarray
    - dask
    - netCDF4
    - bottleneck
    - matplotlib 
    - cartopy
    - scikit
    - scipy 
    - matplotlib
    - basemap
    - opencv-python
    - iris
