name: oceanography
channels:
  - conda-forge
  - pyviz
dependencies:
  - python=3.7
  - jupyter
  - cartopy
  - pip
  - yaml
  - netcdf4
  - basemap
  # A lot of the packages gave error with conda, simply install pip and run pip for rest of packages
  - pip:
    - pyyaml
    - dask
    #- dask distributed --upgrade
    - distributed
    - bottleneck
    - xarray>=0.11.3
    - esmpy
    - xarray
    - geopy
    - xesmf
    - xgcm>=0.2.0
    - Ipython
    - tqdm
    - pytest
    - pytest-cov
    - pytest-env
    - codecov
    - pycodestyle
    - ipython
    - numpydoc
    - sphinx
    - sphinx_rtd_theme
    - nbsphinx
    - cmocean
    - eofs
    - gsw
    - pycwt
    - seaborn
    - pyviz
    - jupyterlab
    - nodejs 
    - ffmpeg
    - oceanspy # Won't install
    - xhistogram
    - ffmpeg
    - xmitgcm>=0.3.0